### ISSUE TITLE
Error when trying to run classifier

### ISSUE THREAD

**Issue by jlooper** [googlecodelabs/edgetpu-classifier#1]
I have a Coral board and am able to run demos using the camera, so I know my hardware setup is fine; I'd like to complete this codelab but in step 4, when I try to run main.py, I get a segmentation fault:

I'm running:

```
python3 main.py \
  --model=inception_v2_224_quant.tflite \
  --labels=imagenet_labels.txt
```

and the error is:

glvideomixer name=mixer background=black ! glimagesink name=glsink sync=False qos=False
v4l2src device=/dev/video1 ! video/x-raw,framerate=24/1,format=YUY2,height=600,width=800 ! glupload ! tee name=t
t. ! glupload ! queue ! mixer.
overlaysrc name=overlay ! video/x-raw,format=BGRA,height=600,width=800 ! glupload ! queue max-size-buffers=1 ! mixer.
t. ! queue leaky=downstream max-size-buffers=1 ! glfilterbin filter=glcolorscale ! video/x-raw,format=RGBA,height=168,width=224 ! videoconvert ! video/x-raw,format=RGB,height=168,width=224 ! videobox autocrop=True ! video/x-raw,height=224,width=224 ! appsink sync=False drop=True emit-signals=True name=appsink max-buffers=1

(main.py:3683): Gdk-CRITICAL **: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed
...
(main.py:3683): Gtk-CRITICAL **: gtk_icon_theme_choose_icon_for_scale: assertion 'scale >= 1' failed
...
(main.py:3683): Gdk-CRITICAL **: gdk_monitor_get_workarea: assertion 'GDK_IS_MONITOR (monitor)' failed
...
Segmentation fault

Is there some error stopping the code from understanding I use a Coral camera, not my USB webcam?

thanks!

**Comment by devunwired** [comment]
Thanks for your feedback. A couple follow up questions:

1. Do you have a display connected via HDMI? The codelab assumes this and the error you are reporting seems related to being unable to determine display parameters.
1. The command you posted assumes the Coral camera on `/dev/video0`, but the error output you attached lists `/dev/video1` (where a USB camera would typically appear). Has `main.py` been modified at all to change the [default source parameter](https://github.com/googlecodelabs/edgetpu-classifier/blob/master/classifier-start/main.py#L57)?

**Comment by Alekxos** [comment]
@devunwired I just tried the same tutorial also with the command: `python3 main.py --model=inception_v2_224_quant.tflite --labels=imagenet_labels.txt
`
and experience the exact same error:
```
glvideomixer name=mixer background=black ! glimagesink name=glsink sync=False qos=False
v4l2src device=/dev/video0 ! video/x-raw,format=YUY2,framerate=30/1,width=1280,height=720 ! glupload ! tee name=t
t. ! glupload ! queue ! mixer.
overlaysrc name=overlay ! video/x-raw,format=BGRA,width=1280,height=720 ! glupload ! queue max-size-buffers=1 ! mixer.
t. ! queue max-size-buffers=1 leaky=downstream ! glfilterbin filter=glcolorscale ! video/x-raw,format=RGBA,width=16,height=9 ! videoconvert ! video/x-raw,format=RGB,width=16,height=9 ! videobox autocrop=True ! video/x-raw,width=16,height=9 ! appsink name=appsink drop=True sync=False emit-signals=True max-buffers=1
```
followed by 
```
(main.py:3506): Gdk-CRITICAL **: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed
...
(main.py:3506): Gtk-CRITICAL **: gtk_icon_theme_choose_icon_for_scale: assertion 'scale >= 1' failed
...
(main.py:3506): Gdk-CRITICAL **: gdk_monitor_get_workarea: assertion 'GDK_IS_MONITOR (monitor)' failed
...
Segmentation fault
```

I was also able to run the two sample demos here: https://coral.withgoogle.com/docs/dev-board/camera/#run-a-demo-with-the-camera

on a local server without a problem, but it failed to run on two different HDMI outputs. I have connected the Coral Board directly to the HDMI 1 port on the monitor, use a wifi connection instead of the serial console, and otherwise only the camera, power, and data (OTG) ports are occupied.
Since the monitor output resolution is 3840x2160, I removed the line `mode=1920x1080` from the file `/etc/xdg/weston/weston.ini`. Same error regardless. Only other line here is the preceding one: name=`HDMI-A-1`

To answer your earlier questions:
1. Yes, the display is connected by a double-pronged HDMI cable and tested on both an LG and Samsung monitor.
2. I didn't tamper with main.py, default source parameter is still default=`'1280x720'`.

Any suggestions? Seems to be a problem with scaling the camera input to the monitor resolution but I'm not familiar with how GdkMonitor works.

@jlooper Have you found a fix?

**Comment by jlooper** [comment]
After rereading the OP I realize that I don't have an HDMI cable, I just have the camera connected to the board via USB C cables. It seems like a better bet is to use my webcam. I would prefer, though, to use the camera as we can on the Coral demos. I'll update this if I can get it working via webcam.

**Comment by devunwired** [comment]
@jlooper I also forgot to mention in my previous comment that you can modify the script to run without a display connected, you just have to change [this parameter](https://github.com/googlecodelabs/edgetpu-classifier/blob/master/classifier-start/main.py#L53) to `Display.NONE`.

I have not personally tested a USB camera connected via the USB-C port, only with the dedicated USB-A host port. If you are using anything other than the Coral CSI camera, you'll want to read [these instructions](https://coral.withgoogle.com/docs/dev-board/camera/#connect-a-usb-camera) to make sure you pass a source parameter to the script that your camera actually supports.

@Alekxos If the issues are not specific to the codelab and you are experiencing the same result with the product demos, I would recommend [Coral Support](https://coral.withgoogle.com/resources/#more-info-and-help).

You can also try `Display.WINDOW` on a monitor where you suspect there is an issue matching the scaling ratios between the camera and the full monitor resolution.

**Comment by jlooper** [comment]
hi, I'm failing on getting a streaming server working with my Logitec webcam, but I'm going to go back and try to get the Coral camera back online. I just retested and the base demo with coral camera and streaming server does work:

```
edgetpu_classify_server \
--model ${DEMO_FILES}/mobilenet_v2_1.0_224_quant_edgetpu.tflite \
--labels ${DEMO_FILES}/imagenet_labels.txt
```

That does work. Let me try to get that Coral camera working. Thank you!

**Comment by devunwired** [comment]
Note that the codelab does not include the code for the streaming server used in the Coral demos. It is designed only to work over HDMI (if a display is used).

**Comment by jlooper** [comment]
ah, you know, I think that's the kicker. Either I should go buy an HDMI cable or we could perhaps find a way to tweak the demo to allow streaming....

**Comment by devunwired** [comment]
If you are looking for the source code of the built-in camera demos, it can be found [here](https://coral.googlesource.com/edgetpuvision/+/refs/heads/release-chef).

This repository simply contains the project paired with the [EdgeTPU Classifier Codelab](https://codelabs.developers.google.com/codelabs/edgetpu-classifier)

**Comment by Guillaume-slize** [comment]
> @jlooper I also forgot to mention in my previous comment that you can modify the script to run without a display connected, you just have to change [this parameter](https://github.com/googlecodelabs/edgetpu-classifier/blob/master/classifier-start/main.py#L53) to `Display.NONE`.

Thanks a lot, It will save me some time :)

**Comment by Iorek73** [comment]
@Guillaume-slize 
This code works for me... with the demo model. 

```
export DISPLAY=:0 && edgetpu_detect \
--source /dev/video1:YUY2:1280x720:20/1  \
--model ${DEMO_FILES}/mobilenet_v2_1.0_224_quant_edgetpu.tflite
```

However, if I switch to my own trained .tflite file I get a Segmentation fault error so the problem isn't fully solved.
